import { Metadata } from "next";

type Props = {
  params: Promise<{ locale: string }>;
};

export async function generateMetadata(props: Props): Promise<Metadata> {
  const params = await props.params;
  const locale = params.locale;
  const siteName = process.env.SITE_NAME || "58Solutions";

  const titles = {
    en: "Privacy Policy - Data Protection & Privacy | 58Solutions",
    de: "Datenschutzerklärung - Datenschutz & Privatsphäre | 58Solutions"
  };

  const descriptions = {
    en: "Privacy policy for 58Solutions GmbH. Learn how we collect, use, and protect your personal data in accordance with GDPR and German data protection laws.",
    de: "Datenschutzerklärung für 58Solutions GmbH. Erfahren Sie, wie wir Ihre personenbezogenen Daten gemäß DSGVO und deutschem Datenschutzrecht sammeln, verwenden und schützen."
  };

  return {
    title: titles[locale as keyof typeof titles] || titles.en,
    description: descriptions[locale as keyof typeof descriptions] || descriptions.en,
    robots: {
      index: true,
      follow: true,
    },
  };
}

export default function PrivacyPolicyPage() {
  return (
    <div className="pt-24 md:pt-28 lg:pt-32">
      <section className="py-16 sm:py-20 lg:py-24">
        <div className="px-4 xl:container">
          <div className="mx-auto max-w-4xl">
            <div className="mb-12 text-center">
              <h1 className="mb-6 font-heading text-4xl font-bold text-dark sm:text-5xl dark:text-white">
                Privacy Policy
              </h1>
              <p className="text-lg text-dark-text">
                Data protection and privacy information
              </p>
            </div>

            <div className="prose prose-lg max-w-none dark:prose-invert">
              <div className="rounded-sm bg-white p-8 shadow-sm dark:bg-[#1D232D] lg:p-12">
                <div className="mb-8">
                  <p className="text-base text-dark-text">
                    Our Privacy Policy was last updated on <strong className="text-dark dark:text-white">05. Jan 2024</strong>. It governs the privacy terms of our website, located at <strong className="text-primary">58agents.com</strong>, and the tools we provide you (the &quot;Website\&quot; or the &quot;Service&quot;).
                  </p>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Your Privacy
                  </h2>
                  <p className="text-base text-dark-text leading-relaxed">
                    Our Website follows all legal requirements to protect your privacy. Our Privacy Policy is a legal statement that explains how we may collect information from you, how we may share your information, and how you can limit our sharing of your information. You will see terms in our Privacy Policy that are capitalized. These terms have meanings as described in the Definitions section below.
                  </p>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Definitions
                  </h2>
                  <div className="space-y-4 text-base text-dark-text leading-relaxed">
                    <p>
                      <strong className="text-dark dark:text-white">Personal Data:</strong> Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
                    </p>
                    <p>
                      <strong className="text-dark dark:text-white">Usage Data:</strong> Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                    </p>
                    <p>
                      <strong className="text-dark dark:text-white">Cookies:</strong> Cookies are small pieces of data stored on a User&apos;s device.
                    </p>
                    <p>
                      <strong className="text-dark dark:text-white">Data Controller:</strong> Data Controller means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
                    </p>
                    <p>
                      <strong className="text-dark dark:text-white">Data Processors (or Service Providers):</strong> Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
                    </p>
                    <p>
                      <strong className="text-dark dark:text-white">Data Subject:</strong> Data Subject is any living individual who is the subject of Personal Data.
                    </p>
                    <p>
                      <strong className="text-dark dark:text-white">User:</strong> The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
                    </p>
                  </div>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Information Collection And Use
                  </h2>
                  <p className="text-base text-dark-text leading-relaxed">
                    We collect several different types of information for various purposes to provide and improve our Service to you.
                  </p>
                </div>

                <div className="mb-8">
                  <h3 className="mb-4 font-heading text-xl font-medium text-dark dark:text-white">
                    Types of Data Collected
                  </h3>
                  <div className="space-y-6 text-base text-dark-text leading-relaxed">
                    <div>
                      <h4 className="mb-2 font-heading text-lg font-medium text-dark dark:text-white">
                        Personal Data
                      </h4>
                      <p>
                        While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (&quot;Personal Data&quot;). Personally identifiable information may include, but is not limited to: Email address, Name, Address, State, Province, ZIP/Postal code, City, Cookies and Usage Data. We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.
                      </p>
                    </div>
                    
                    <div>
                      <h4 className="mb-2 font-heading text-lg font-medium text-dark dark:text-white">
                        Usage Data
                      </h4>
                      <p>
                        We may also collect information how the Service is accessed and used (&quot;Usage Data&quot;). This Usage Data may include information such as your computer&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                      </p>
                    </div>
                    
                    <div>
                      <h4 className="mb-2 font-heading text-lg font-medium text-dark dark:text-white">
                        Tracking & Cookies Data
                      </h4>
                      <p>
                        We use cookies and similar tracking technologies to track the activity on our Service and hold certain information. Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service. Examples of Cookies we use: session cookies (we use these cookies to operate our Service) and preference cookies (we use these cookies to remember your preferences and various settings).
                      </p>
                    </div>
                  </div>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Use of Data
                  </h2>
                  <p className="mb-4 text-base text-dark-text leading-relaxed">
                    We use the collected data for various purposes:
                  </p>
                  <ul className="space-y-2 text-base text-dark-text">
                    <li className="flex items-start">
                      <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                      To provide and maintain our Service
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                      To notify you about changes to our Service
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                      To allow you to participate in interactive features of our Service when you choose to do so
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                      To provide customer support
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                      To gather analysis or valuable information so that we can improve our Service
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                      To monitor the usage of our Service
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                      To detect, prevent and address technical issues
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                      To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information
                    </li>
                  </ul>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Retention of Data
                  </h2>
                  <div className="space-y-4 text-base text-dark-text leading-relaxed">
                    <p>
                      We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                    </p>
                    <p>
                      We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
                    </p>
                  </div>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Transfer Of Data
                  </h2>
                  <div className="space-y-4 text-base text-dark-text leading-relaxed">
                    <p>
                      Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.
                    </p>
                    <p>
                      We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
                    </p>
                    <p>
                      Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
                    </p>
                  </div>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Disclosure Of Data
                  </h2>
                  <div className="space-y-4 text-base text-dark-text leading-relaxed">
                    <div>
                      <h4 className="mb-2 font-heading text-lg font-medium text-dark dark:text-white">
                        Business Transaction
                      </h4>
                      <p>
                        If we are involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.
                      </p>
                    </div>
                    
                    <div>
                      <h4 className="mb-2 font-heading text-lg font-medium text-dark dark:text-white">
                        Disclosure for Law Enforcement
                      </h4>
                      <p>
                        Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                      </p>
                    </div>
                  </div>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Security Of Data
                  </h2>
                  <p className="text-base text-dark-text leading-relaxed">
                    The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
                  </p>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)
                  </h2>
                  <div className="space-y-4 text-base text-dark-text leading-relaxed">
                    <p>
                      If you are from the European Economic Area (EEA), 58agents legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.
                    </p>
                    <p>58agents may process your Personal Data because:</p>
                    <ul className="space-y-2">
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        We need to perform a contract with you
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        You have given us permission to do so
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        The processing is in our legitimate interests and it&apos;s not overridden by your rights
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        For payment processing purposes
                      </li>
                    </ul>
                  </div>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Your Data Protection Rights Under General Data Protection Regulation (GDPR)
                  </h2>
                  <div className="space-y-4 text-base text-dark-text leading-relaxed">
                    <p>
                      If you are a resident of the European Economic Area (EEA), you have certain data protection rights. 58agents aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
                    </p>
                    <p>
                      If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.
                    </p>
                    <p>In certain circumstances, you have the following data protection rights:</p>
                    <ul className="space-y-2">
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        The right to access, update or to delete the information we have on you.
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        The right to object. You have the right to object to our processing of your Personal Data.
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        The right of restriction. You have the right to request that we restrict the processing of your personal information.
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        The right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format.
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        The right to withdraw consent. You also have the right to withdraw your consent at any time where 58agents relied on your consent to process your personal information.
                      </li>
                    </ul>
                    <p>
                      Please note that we may ask you to verify your identity before responding to such requests.
                    </p>
                    <p>
                      You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
                    </p>
                  </div>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Service Providers
                  </h2>
                  <div className="space-y-4 text-base text-dark-text leading-relaxed">
                    <p>
                      We may employ third party companies and individuals to facilitate our Service (&quot;Service Providers&quot;), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.
                    </p>
                    <p>
                      These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
                    </p>
                  </div>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Consent to the use of cookies
                  </h2>
                  <div className="space-y-4 text-base text-dark-text leading-relaxed">
                    <p>
                      For our website to function properly we use cookies. To obtain your valid consent for the use and storage of cookies in the browser you use to access our website and to properly document this we use a consent management platform: CookieFirst. This technology is provided by Digital Data Solutions BV, Plantage Middenlaan 42a, 1018 DH, Amsterdam, The Netherlands. Website: <a href="https://cookiefirst.com" className="text-primary hover:text-primary/80" target="_blank" rel="noopener noreferrer">https://cookiefirst.com</a> referred to as CookieFirst.
                    </p>
                    <p>
                      When you access our website, a connection is established with CookieFirst&apos;s server to give us the possibility to obtain valid consent from you to the use of certain cookies. CookieFirst then stores a cookie in your browser in order to be able to activate only those cookies to which you have consented and to properly document this. The data processed is stored until the predefined storage period expires or you request to delete the data. Certain mandatory legal storage periods may apply notwithstanding the aforementioned.
                    </p>
                    <p>
                      CookieFirst is used to obtain the legally required consent for the use of cookies. The legal basis for this is article 6(1)(c) of the General Data Protection Regulation (GDPR).
                    </p>
                  </div>
                </div>

                <div className="mb-8">
                  <h3 className="mb-4 font-heading text-xl font-medium text-dark dark:text-white">
                    Data processing agreement
                  </h3>
                  <p className="text-base text-dark-text leading-relaxed">
                    We have concluded a data processing agreement with CookieFirst. This is a contract required by data protection law, which ensures that data of our website visitors is only processed in accordance with our instructions and in compliance with the GDPR.
                  </p>
                </div>

                <div className="mb-8">
                  <h3 className="mb-4 font-heading text-xl font-medium text-dark dark:text-white">
                    Server log files
                  </h3>
                  <div className="space-y-4 text-base text-dark-text leading-relaxed">
                    <p>
                      Our website and CookieFirst automatically collect and store information in so-called server log files, which your browser automatically transmits to us. The following data is collected:
                    </p>
                    <ul className="space-y-2">
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        Your consent status or the withdrawal of consent
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        Your anonymised IP address
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        Information about your Browser
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        Information about your Device
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        The date and time you have visited our website
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        The webpage url where you saved or updated your consent preferences
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        The approximate location of the user that saved their consent preference
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2 mt-2 h-1.5 w-1.5 rounded-full bg-primary"></span>
                        A universally unique identifier (UUID) of the website visitor that clicked the cookie banner
                      </li>
                    </ul>
                  </div>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Links To Other Sites
                  </h2>
                  <div className="space-y-4 text-base text-dark-text leading-relaxed">
                    <p>
                      Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party&apos;s site. We strongly advise you to review the Privacy Policy of every site you visit.
                    </p>
                    <p>
                      We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                    </p>
                  </div>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Children&apos;s Privacy
                  </h2>
                  <div className="space-y-4 text-base text-dark-text leading-relaxed">
                    <p>
                      Our Service does not address anyone under the age of 18 (&quot;Children&quot;).
                    </p>
                    <p>
                      We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
                    </p>
                  </div>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Changes To This Privacy Policy
                  </h2>
                  <div className="space-y-4 text-base text-dark-text leading-relaxed">
                    <p>
                      This Privacy Policy is effective as of 01 October 2019 and will remain in effect except with respect to any changes in its provisions in the future, which will be in effect immediately after being posted on this page.
                    </p>
                    <p>
                      We reserve the right to update or change our Privacy Policy at any time and you should check this Privacy Policy periodically. Your continued use of the Service after we post any modifications to the Privacy Policy on this page will constitute your acknowledgment of the modifications and your consent to abide and be bound by the modified Privacy Policy.
                    </p>
                    <p>
                      If we make any material changes to this Privacy Policy, we will notify you either through the email address you have provided us, or by placing a prominent notice on our website.
                    </p>
                  </div>
                </div>

                <div className="mb-8">
                  <h2 className="mb-4 font-heading text-2xl font-bold text-dark dark:text-white">
                    Contact Us
                  </h2>
                  <p className="text-base text-dark-text leading-relaxed">
                    If you have any questions about this Privacy Policy, please contact us by sending us an E-Mail to{" "}
                    <a href="mailto:hey@58agents.com" className="text-primary hover:text-primary/80">
                      hey@58agents.com
                    </a>.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}